version: 0.2

env:
  parameter-store:
    DOCKER_HUB_USERNAME: "docker-hub-username"
    DOCKER_HUB_PASSWORD: "docker-hub-password"

phases:
  pre_build:
    commands:
      - echo Logging into Docker Hub...
      - docker login -u ${DOCKER_HUB_USERNAME} --password-stdin ${DOCKER_HUB_PASSWORD}
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t scionaltera:agony-engine -f src/main/docker/codebuild/Dockerfile .
#      - docker tag scionaltera:agony-engine latest
  post_build:
    commands:
      - echo Pushing the Docker image..
#      - docker push scionaltera:agony-engine:latest
