agonyengine:
  maps:
    default: "5231e20f-0658-4685-9396-6e69ebfb2c3b"

spring:
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

logging:
  level:
    org.springframework.messaging: DEBUG
    org.springframework.web: DEBUG
